services:
  identity-service:
    build:
      context: .
      dockerfile: backend/identity-service/Dockerfile.dev
    ports:
      - "3002:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - backend/identity-service/.env
    depends_on:
      identity-db:
        condition: service_healthy

  identity-db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: identity
    volumes:
      - identity-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  identity-db-test:
    image: postgres:17-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: identity_test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  identity-db-data: